language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - "pip install -r requirements.txt"

before_script:
  # - psql -c 'create database store_manager_db;' -U postgres
  # - psql -c 'create database test_db;' -U postgres
  # - psql -c "CREATE USER andela WITH PASSWORD 'bootcamp';" -U postgres
  # - python app/db_installer.py

# command to run tests
script:
  - python3 -m pytest --cov=app/
  
after_success:
  - coveralls